blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/E3SM-Project/QuickView/issues/new?template=feature_request.md
    about: Suggest an idea for QuickView
  - name: Bug Report
    url: https://github.com/E3SM-Project/QuickView/issues/new?template=bug_report.md
    about: Report a bug in QuickView
  - name: Question
    url: https://github.com/E3SM-Project/QuickView/discussions
    about: Ask questions and discuss with the community
