site_name: EAM QuickView 1.0 Documentation
theme: "material"
plugins:
  - search
  - mkdocstrings
nav:
  - Home: README.md
  - Installation and Launch:
      - For End Users:      setup/for_end_users.md
      - For App Developers: setup/for_app_developers.md
  - User's Guide:
      - Key Reminders:      userguide/reminders.md
      - Connectivity Files: userguide/connectivity.md
      - GUI Overview:       userguide/gui_overview.md
      - Toolbar:            userguide/toolbar.md
      - Control Panel:      userguide/control_panel.md
      - Viewport:           userguide/viewport.md
      - Camera Widget:      userguide/camera.md
  - Plans: future.md
markdown_extensions:
  - attr_list
