site_name: EAM QuickView Documentation
theme: 'material'
plugins:
  - search
  - mkdocstrings
nav:
  - Home: README.md
  - Tutorials:
    - QuickView : tutorials/eamapp.md
markdown_extensions:
  - attr_list
