site_name: EAM QuickView 1.0 Documentation
theme: "material"
plugins:
  - search
  - mkdocstrings
nav:
  - Home: README.md
  - Install and Launch:
      - For End Users:      setup/for_end_users.md
      - For App Developers: setup/for_app_developers.md
  - User's Guide:
      - Key Reminders:      userguide/reminders.md
      - Connectivity Files: userguide/connectivity.md
      - Data File Format:   userguide/data_requirements.md
      - GUI Overview:       userguide/gui_overview.md
      - Toolbar:            userguide/toolbar.md
      - Control Panel:      userguide/control_panel.md
      - Viewport:           userguide/viewport.md
  - Plans: future.md
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
